# Generated by Django 4.0.3 on 2022-10-08 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_user_id_tweet_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
    ]
