# Generated by Django 4.0.3 on 2022-10-08 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_user_id_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
