# Generated by Django 4.0.3 on 2022-11-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_comment_liked_by_remove_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='api.tweet'),
        ),
    ]
