# Generated by Django 4.0.3 on 2022-11-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tweet_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='followers',
        ),
    ]
